### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute '_get_distribution_strategy'

### ISSUE THREAD

**Issue by vicenzocesconetto** [chow-vincent/tennis_action_recognition#3]
I keep getting the above issue trying to run lrcnn_train.py  but the only answer I found was: "you are mixing Tensorflow and Keras" but we can see that this code doesn't mix. How does one solve this problem?

**Comment by chow-vincent** [comment]
Strange, I am not seeing this issue running the code with python3. For the imports, maybe try adding `tensorflow` in front of any calls to keras, e.g. `from tensorflow.keras.optimizers import Adam`.
